#simulation Time
MAX_SIMULATION_TIME = 4000
SLOT_TIME =  20

MAX_JOBS = 85
JOB_ATTRIBUTES = 3
MAX_RS = 6
SENSERS_PER_CLUSTER = 6

#fitness perameters
#Latency weight 
ALPHA = 1
#Energy weight
BETA = 0
#Cost weight 
GAMA = 0

#RESOURCE MANAGEMENT OPTIONS
DEFAULT_RM = 0
GA_RM = 1
AI_RM = 2

#resource management approch
RM_TYPE = AI_RM

#cloud server attributes
CLOUD_COST_UNIT_TIME = 0.01
CLOUD_CPU_SPEED = 48000

#bandwidth
FD_BANDWIDTH1 = 1
FD_BANDWIDTH2 = 2
FD_BANDWIDTH3 = 3

#RAM capacity
FD_RAM1 = 1000
FD_RAM2 = 2000
FD_RAM3 = 3000

#capacity
FD_CAPACITY1 = 10
FD_CAPACITY2 = 15
FD_CAPACITY3 = 20
	
#CPU speed instructions per second
CPU_SPEED1 = 10
CPU_SPEED2 = 20
CPU_SPEED3 = 30
	
#latency
LATENCY_CS_FR = 50
LATENCY_ED_FR = 1

#RAM swaping unit time
RAM_SWAP_UNIT = 2

#task types
SENSER_TYPE = 1
ACTUATER_TYPE = 5
FOG_TYPE = 6

#FOURE types of jobs - one senser has one type of job
#Application 1
#CAMRA_SEN,CAMRA_PRO, ROAD_DISPLAY
CAMRA_SEN = 1 
#GPSPOS_SEN,GPSPOS_PRO,GPSPOS_STORE
GPSPOS_SEN= 2

#Application 2
#INDLOOP_SEN,INDLOOP_PRO,ROAD_DISPLAY
INDLOOP_SEN = 3
#MICWAVE_SEN,MICWAVE_PRO,MICWAVE_STORE
MICWAVE_SEN = 4

#actuater
ROAD_DISPLAY = 5
CONT_DISPLAY = 6

#node genarated tasks
CAMRA_PRO = 7
INDLOOP_PRO = 8
GPSPOS_PRO = 9
MICWAVE_PRO = 10

#actuater
CAMRA_STORE =11
INDLOOP_STORE = 12
GPSPOS_STORE = 13
MICWAVE_STORE = 14

#number of instructions (in bytes) in each job Type
NO_INSTRUCTIONS1 = 10
NO_INSTRUCTIONS2 = 12
NO_INSTRUCTIONS3 = 14
NO_INSTRUCTIONS4 = 15
NO_INSTRUCTIONS5 = 0
NO_INSTRUCTIONS6 = 0
NO_INSTRUCTIONS7 = 12
NO_INSTRUCTIONS8 = 14
NO_INSTRUCTIONS9 = 13
NO_INSTRUCTIONS10 = 10
NO_INSTRUCTIONS11 = 0
NO_INSTRUCTIONS12 = 0
NO_INSTRUCTIONS13 = 0
NO_INSTRUCTIONS14 = 0

#job data size
DATA_SIZE1 = 500
DATA_SIZE2 = 1000
DATA_SIZE3 = 1500
DATA_SIZE4 = 2000

INTERVEL_GAP = NO_INSTRUCTIONS4 / CPU_SPEED1 
