#simulation Time
MAX_SIMULATION_TIME = 30000
SLOT_TIME0 = 30

MAX_JOBS = 130   #take care for AI dataset settings
JOB_ATTRIBUTES = 3
MAX_RS = 9              #take care for AI dataset settings
SENSERS_PER_CLUSTER = 6 #take care for AI dataset settings

#fitness perameters
#Latency weight 
ALPHA = 1.
#Energy weight
BETA = 0.0
#Cost weight 
GAMA = 0.0

#RESOURCE MANAGEMENT OPTIONS
DEFAULT_RM = 0
GA_RM = 1
AI_RM = 2
RL_RM = 3

#resource management approch
RM_TYPE = DEFAULT_RM

#cloud server attributes
CLOUD_COST_UNIT_TIME = 0.01
CLOUD_CPU_SPEED = 48000

#bandwidth
FD_BANDWIDTH1 = 1
FD_BANDWIDTH2 = 2
FD_BANDWIDTH3 = 3

#RAM capacity
FD_RAM1 = 1000
FD_RAM2 = 2000
FD_RAM3 = 3000

#capacity
FD_CAPACITY1 = 10
FD_CAPACITY2 = 15
FD_CAPACITY3 = 20
	
#CPU speed instructions per second
CPU_SPEED1 = 5
CPU_SPEED2 = 10
CPU_SPEED3 = 20
	
#latency
LATENCY_CS_FR = 50
LATENCY_ED_FR = 1

#RAM swaping unit time
RAM_SWAP_UNIT = 1

#task types
SENSER_TYPE = 1
ACTUATER_TYPE = 5
FOG_TYPE = 6

#FOURE types of jobs - one senser has one type of job
#Application 1
#CAMRA_SEN,VEHICLE_IDENTIFICATION, ACTION_ON_VEHICLE
CAMRA_SEN = 1 
#TRAFIC_SEN,TRAFIC_LOCATION,ACTION_CLEAR_TRAFIC
TRAFIC_SEN= 2

#node genarated tasks
VEHICLE_IDENTIFICATION = 3
TRAFIC_LOCATION = 4

#actuater
ACTION_ON_VEHICLE = 5
ACTION_CLEAR_TRAFIC = 6


#number of instructions (in bytes) in each job Type
NO_INSTRUCTIONS1 = 10
NO_INSTRUCTIONS2 = 12
NO_INSTRUCTIONS3 = 120
NO_INSTRUCTIONS4 = 130
NO_INSTRUCTIONS5 = 0
NO_INSTRUCTIONS6 = 0
NO_INSTRUCTIONS7 = 12
NO_INSTRUCTIONS8 = 14
NO_INSTRUCTIONS9 = 13
NO_INSTRUCTIONS10 = 10
NO_INSTRUCTIONS11 = 0
NO_INSTRUCTIONS12 = 0
NO_INSTRUCTIONS13 = 0
NO_INSTRUCTIONS14 = 0

#job data size
DATA_SIZE1 = 500
DATA_SIZE2 = 1000
DATA_SIZE3 = 1500
DATA_SIZE4 = 2000

INTERVEL_GAP = NO_INSTRUCTIONS4 / CPU_SPEED1 

SLOT_TIME =  INTERVEL_GAP * SENSERS_PER_CLUSTER + INTERVEL_GAP + SLOT_TIME0
